PetalburgCity_House2_MapScripts::
	.byte 0

PetalburgCity_House2_EventScript_Woman::
	msgbox PetalburgCity_House2_Text_MovedFromJohto, MSGBOX_NPC
	end

PetalburgCity_House2_EventScript_SchoolKid::
	msgbox PetalburgCity_House2_Text_Grandma, MSGBOX_NPC
	end

PetalburgCity_House2_Text_MovedFromJohto:
	.string "Ever since Jo moved here from Johto to\n"
	.string "become the Gym Leader, things have\n"
	.string "really picked up in the city.\p"
	.string "So many new trainers showed up that we\n"
	.string "even built our own Trainer School.$"

PetalburgCity_House2_Text_Grandma:
	.string "My grandma is so cool!\p"
	.string "She raises baby Pokémon!\p"
	.string "The Gym Leader even lets them play\n"
	.string "in the pool by the Gym!\p"
	.string "I wish I could play in the pool\n"
	.string "by the Gym...$"

